import {useEffect,useRef,useState} from 'react';
import type {DesignRecord,EditorAction} from '../../../packages/app-model/src/index';
import type {Vec2,Node,BezierSegment,DesignObject,Master} from '../../../packages/core/src/types';
import type {EditorGeometry,EditorRender} from './editor-protocol';
import {CanvasGeometryCache,GeometryPreview,designTransform,previewControlPoint,previewMaster,viewportBox,type CanvasTransform,type LiveEdit} from './canvas-preview';
import {flattenEdge} from '../../../packages/core/src/topology';
import {displayPixelAspect} from './source-aspect';
export type Tool='select'|'node'|'pen'|'line'|'fill'|'erase'|'pixel'|'zoom'|'cleanup-area';
export function toolAvailable(tool:Tool,document:DesignRecord):boolean {
  if(tool==='cleanup-area')return document.kind==='size'&&!!document.master.raster;
  if(tool==='pixel')return document.kind==='size';
  return !document.master.raster||tool==='zoom';
}
export interface Selection{edgeId?:string;nodeId?:string;objectIds:string[]}
export interface ViewOptions{boundaries:boolean;nodes:boolean;repeat:boolean;trueProportion:boolean;grid:boolean;changes:boolean;overrides:boolean;hidden:boolean}
interface Props{document:DesignRecord;renderedDocument?:DesignRecord;renderPending?:boolean;geometry:EditorGeometry;render:EditorRender;tool:Tool;color:number;selection:Selection;onSelect:(s:Selection)=>void;onAction:(action:EditorAction)=>void;onFill:(point:Vec2,pick:boolean)=>void;options:ViewOptions;viewCommand:{kind:'fit'|'actual'|'in'|'out'|'focus';serial:number;point?:Vec2};disabled:boolean;onZoom:(value:number)=>void;onCleanupAreaDone?:()=>void}
interface Drag{kind:'pan'|'node'|'handle'|'object'|'draw'|'pixel'|'cleanup-area';start:Vec2;last:Vec2;x:number;y:number;moved:boolean;nodeId?:string;edgeId?:string;segIndex?:number;key?:'c1'|'c2';original?:Vec2;objectIds?:string[];pixels?:Map<string,{x:number;y:number;colorIndex:number|null}>;live?:LiveEdit;master?:Master;shownMaster?:Master;changedEdges?:Set<string>}
const sq=(p:Vec2,q:Vec2)=>(p.x-q.x)**2+(p.y-q.y)**2;
/** Store design-relative coordinates so the area follows size, zoom and true proportion. */
export function cleanupAreaFromDrag(a:Vec2,b:Vec2,width:number,height:number){
  const clamp=(n:number)=>Math.max(0,Math.min(1,n));
  const x=clamp(Math.min(a.x,b.x)/width),y=clamp(Math.min(a.y,b.y)/height),right=clamp(Math.max(a.x,b.x)/width),bottom=clamp(Math.max(a.y,b.y)/height);
  return right>x&&bottom>y?{x,y,w:right-x,h:bottom-y}:undefined;
}
/** Clip before walking the grid so a drag outside the artboard stays bounded. */
function pixelLine(a:Vec2,b:Vec2,width:number,height:number,visit:(x:number,y:number)=>void){
  const dx=b.x-a.x,dy=b.y-a.y;let low=0,high=1;
  for(const [p,q]of[[-dx,a.x],[dx,width-1-a.x],[-dy,a.y],[dy,height-1-a.y]]){if(p===0){if(q<0)return;}else{const t=q/p;if(p<0)low=Math.max(low,t);else high=Math.min(high,t);if(low>high)return;}}
  let x=Math.round(a.x+low*dx),y=Math.round(a.y+low*dy);const endX=Math.round(a.x+high*dx),endY=Math.round(a.y+high*dy),ax=Math.abs(endX-x),ay=-Math.abs(endY-y),sx=x<endX?1:-1,sy=y<endY?1:-1;let error=ax+ay;
  for(;;){visit(x,y);if(x===endX&&y===endY)break;const twice=2*error;if(twice>=ay){error+=ay;x+=sx;}if(twice<=ax){error+=ax;y+=sy;}}
}
export default function DesignCanvas(props:Props){
  const ref=useRef<HTMLCanvasElement>(null),host=useRef<HTMLDivElement>(null),latest=useRef(props);latest.current=props;
  const view=useRef({zoom:1,x:0,y:0,w:800,h:600}),bitmap=useRef<HTMLCanvasElement|undefined>(undefined),changeBitmap=useRef<HTMLCanvasElement|undefined>(undefined),buckets=useRef(new Map<string,string[]>()),owners=useRef(new Map<string,DesignObject>()),nodeFlags=useRef(new Map<string,{locked:boolean;visible:boolean}>()),pixelAnchor=useRef<Vec2|undefined>(undefined),frame=useRef(0),space=useRef(false),path=useRef<{p:Vec2;c?:Vec2;nodeId?:string}[]>([]),hover=useRef<Vec2|undefined>(undefined),drag=useRef<Drag|undefined>(undefined),retained=useRef<Drag|undefined>(undefined),[drawing,setDrawing]=useState(false);
  const cache=useRef<CanvasGeometryCache|undefined>(undefined),chosenEdges=useRef(new Set<string>()),chosenNodes=useRef(new Set<string>()),changes=useRef(new Set<string>()),faceChanges=useRef(new Set<string>()),scene=useRef<HTMLCanvasElement|undefined>(undefined),overlay=useRef<HTMLCanvasElement|undefined>(undefined),sceneDirty=useRef(true),overlayDirty=useRef(true),sceneVersion=useRef(0),preview=useRef<{value:GeometryPreview;cache:CanvasGeometryCache;master:Master;edit?:LiveEdit;scene:number}|undefined>(undefined);
  const renderedMaster=props.renderedDocument?.master??props.document.master,cacheGeometry=useRef<EditorGeometry|undefined>(undefined);
  const dims=()=>{const p=latest.current,aspect=displayPixelAspect(p.document.master,p.document.kind,p.render,p.options.trueProportion);return {sx:p.render.widthPx/p.document.master.bounds.w,sy:p.render.heightPx*aspect/p.document.master.bounds.h,width:p.render.widthPx,height:p.render.heightPx*aspect};};
  const toScreen=(p:Vec2)=>{const v=view.current,d=dims();return{x:v.x+p.x*d.sx*v.zoom,y:v.y+p.y*d.sy*v.zoom};};
  const toDesign=(p:Vec2)=>{const v=view.current,d=dims();return{x:(p.x-v.x)/(d.sx*v.zoom),y:(p.y-v.y)/(d.sy*v.zoom)};};
  const selectedEdges=()=>chosenEdges.current;
  const displayedMaster=()=>{const held=retained.current;return held?.master&&held.live?(held.shownMaster??=previewMaster(held.master,held.live)):latest.current.document.master;};
  const transform=():CanvasTransform=>{const p=latest.current,v=view.current,d=dims();return{x:v.x,y:v.y,ax:d.sx*v.zoom,ay:d.sy*v.zoom,ratio:Math.min(devicePixelRatio||1,2),width:v.w,height:v.h,gridX:p.render.widthPx/p.document.master.bounds.w,gridY:p.render.heightPx/p.document.master.bounds.h};};
  function invalidate(base=false){if(base)sceneDirty.current=true;overlayDirty.current=true;draw();}
  function beginLive(dr:Drag){const master=displayedMaster(),c=cache.current;if(!c||!['node','handle','object'].includes(dr.kind))return;const nodeIds=new Set<string>(),edgeIds=new Set<string>();if(dr.kind==='node'&&dr.nodeId)nodeIds.add(dr.nodeId);if(dr.kind==='object')for(const id of dr.objectIds??[])for(const edgeId of master.objects.find(o=>o.id===id)?.edgeIds??[])for(const nodeId of master.geometry.edges[edgeId]?.nodeIds??[])nodeIds.add(nodeId);for(const id of nodeIds)for(const edgeId of c.nodeEdges.get(id)??[])edgeIds.add(edgeId);if(dr.kind==='handle'&&dr.edgeId){edgeIds.add(dr.edgeId);const edge=master.geometry.edges[dr.edgeId],nodeId=edge.nodeIds[dr.key==='c1'?dr.segIndex!:dr.segIndex!+1];dr.nodeId=nodeId;for(const id of c.nodeEdges.get(nodeId)??[])edgeIds.add(id);}dr.master=master;dr.changedEdges=new Set(changes.current);for(const id of retained.current?.changedEdges??[])dr.changedEdges.add(id);for(const id of retained.current?.live?.edgeIds??[])dr.changedEdges.add(id);dr.live={kind:dr.kind as LiveEdit['kind'],nodeId:dr.nodeId,edgeId:dr.edgeId,segIndex:dr.segIndex,key:dr.key,delta:{x:0,y:0},nodeIds,edgeIds};preview.current=undefined;overlayDirty.current=true;}
  function line(ctx:CanvasRenderingContext2D,points:Vec2[],color:string,width=1,dashed=false,offset?:Vec2){if(!points.length)return;ctx.beginPath();points.forEach((p,i)=>{const s=toScreen(offset?{x:p.x+offset.x,y:p.y+offset.y}:p);i?ctx.lineTo(s.x,s.y):ctx.moveTo(s.x,s.y);});ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dashed?[5,4]:[]);ctx.stroke();ctx.setLineDash([]);}
  function draw(){if(frame.current)return;frame.current=requestAnimationFrame(()=>{
    frame.current=0;const started=performance.now(),canvas=ref.current,c=cache.current;if(!canvas)return;
    const ctx=canvas.getContext('2d')!,p=latest.current,v=view.current,d=dims(),t=transform(),active=drag.current?.live?drag.current:retained.current,edit=active?.live,model=active?.master??p.document.master;
    if(sceneDirty.current||!scene.current){const target=scene.current??document.createElement('canvas');target.width=canvas.width;target.height=canvas.height;const base=target.getContext('2d')!;base.setTransform(t.ratio,0,0,t.ratio,0,0);base.fillStyle='#e7e9e3';base.fillRect(0,0,v.w,v.h);
      const tile=(x:number,y:number,alpha:number)=>{base.globalAlpha=alpha;base.fillStyle='#fff';base.fillRect(v.x+x*d.width*v.zoom,v.y+y*d.height*v.zoom,d.width*v.zoom,d.height*v.zoom);if(bitmap.current){base.imageSmoothingEnabled=false;base.drawImage(bitmap.current,v.x+x*d.width*v.zoom,v.y+y*d.height*v.zoom,d.width*v.zoom,d.height*v.zoom);}};
      if(p.options.repeat)for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++)if(x||y)tile(x,y,.38);tile(0,0,1);base.globalAlpha=1;scene.current=target;sceneDirty.current=false;sceneVersion.current++;overlayDirty.current=true;
    }
    const needsPreview=!!c&&(changes.current.size>0||faceChanges.current.size>0||!!edit);
    if(needsPreview&&c&&(!preview.current||preview.current.cache!==c||preview.current.master!==model||preview.current.edit!==edit||preview.current.scene!==sceneVersion.current)){
      preview.current={value:new GeometryPreview(c,model,edit,t,scene.current!,active?.changedEdges??changes.current,p.document.kind==='size',faceChanges.current),cache:c,master:model,edit,scene:sceneVersion.current};overlayDirty.current=true;
    }else if(!needsPreview&&preview.current){preview.current=undefined;overlayDirty.current=true;}
    const live=preview.current?.value;
    if(overlayDirty.current||!overlay.current){const visible=c?.visibleEdges(viewportBox(t))??[],target=overlay.current??document.createElement('canvas');target.width=canvas.width;target.height=canvas.height;const over=target.getContext('2d')!;over.setTransform(t.ratio,0,0,t.ratio,0,0);over.save();over.beginPath();over.rect(v.x,v.y,d.width*v.zoom,d.height*v.zoom);over.clip();
      if(p.options.changes&&changeBitmap.current){over.imageSmoothingEnabled=false;over.drawImage(changeBitmap.current,v.x,v.y,d.width*v.zoom,d.height*v.zoom);}
      if(c&&(p.options.boundaries||p.options.hidden)){designTransform(over,t);const boundary=new Path2D(),hiddenPaths=new Path2D();for(const id of visible){if(live?.edgeIds.has(id))continue;const edge=p.document.master.geometry.edges[id],hidden=!!(edge?.strokeHidden||owners.current.get(id)?.hidden);if(edge&&(hidden?p.options.hidden:p.options.boundaries&&edge.width===0))(hidden?hiddenPaths:boundary).addPath(c.edges.get(id)!.path);}over.lineWidth=1/Math.min(t.ax,t.ay);over.strokeStyle='#69777070';over.stroke(boundary);over.strokeStyle='#b6447770';over.setLineDash([5/Math.min(t.ax,t.ay),4/Math.min(t.ax,t.ay)]);over.stroke(hiddenPaths);over.setLineDash([]);over.setTransform(t.ratio,0,0,t.ratio,0,0);}
      if(p.options.grid&&v.zoom>=8){over.beginPath();const hstep=d.height/p.render.heightPx;for(let x=Math.max(0,Math.floor(-v.x/v.zoom));x<=Math.min(p.render.widthPx,Math.ceil((v.w-v.x)/v.zoom));x++){over.moveTo(v.x+x*v.zoom,0);over.lineTo(v.x+x*v.zoom,v.h);}for(let y=Math.max(0,Math.floor(-v.y/v.zoom/hstep));y<=Math.min(p.render.heightPx,Math.ceil((v.h-v.y)/v.zoom/hstep));y++){over.moveTo(0,v.y+y*v.zoom*hstep);over.lineTo(v.w,v.y+y*v.zoom*hstep);}over.strokeStyle='#263f342f';over.lineWidth=.5;over.stroke();}
      if(c){designTransform(over,t);const selected=new Path2D();for(const id of visible)if(chosenEdges.current.has(id)&&!live?.edgeIds.has(id))selected.addPath(c.edges.get(id)!.path);over.strokeStyle='#d87914';over.lineWidth=2.5/Math.min(t.ax,t.ay);over.stroke(selected);over.setTransform(t.ratio,0,0,t.ratio,0,0);}
      if(p.options.nodes||p.tool==='node'){const occupied=new Set<string>();for(const id of c?.nodeIndex.query(viewportBox(t))??[]){if(!chosenNodes.current.has(id)||live?.nodeIds.has(id))continue;const node=p.document.master.geometry.nodes[id];if(!node)continue;const at=toScreen(node.p);if(at.x<0||at.y<0||at.x>v.w||at.y>v.h)continue;const cell=`${Math.floor(at.x/9)},${Math.floor(at.y/9)}`;if(occupied.has(cell)&&id!==p.selection.nodeId)continue;occupied.add(cell);nodeMarker(over,id,node.p);}}
      over.restore();overlay.current=target;overlayDirty.current=false;
    }
    ctx.setTransform(1,0,0,1,0,0);if(live)live.draw(ctx,edit,p.document.kind==='size');else ctx.drawImage(scene.current!,0,0);ctx.setTransform(1,0,0,1,0,0);ctx.drawImage(overlay.current!,0,0);
    ctx.setTransform(t.ratio,0,0,t.ratio,0,0);ctx.save();ctx.beginPath();ctx.rect(v.x,v.y,d.width*v.zoom,d.height*v.zoom);ctx.clip();
    if(live){designTransform(ctx,t);ctx.strokeStyle='#d87914';ctx.lineWidth=2.5/Math.min(t.ax,t.ay);if(edit?.kind==='object'){ctx.save();ctx.translate(edit.delta.x,edit.delta.y);ctx.stroke(live.rigidSelection);ctx.restore();}for(const id of live.edgeIds){if(!chosenEdges.current.has(id)||live.isRigid(id))continue;const currentPath=live.path(id,edit);if(currentPath)ctx.stroke(currentPath);}ctx.setTransform(t.ratio,0,0,t.ratio,0,0);}
    if(p.options.nodes||p.tool==='node'){const ids=live?.nodeIds??new Set<string>();let count=0;for(const id of ids){if(!chosenNodes.current.has(id))continue;const node=model.geometry.nodes[id];if(!node)continue;const moved=edit?.nodeIds.has(id)?{x:node.p.x+edit.delta.x,y:node.p.y+edit.delta.y}:node.p,at=toScreen(moved);if(at.x<0||at.y<0||at.x>v.w||at.y>v.h)continue;if(++count>1500&&id!==p.selection.nodeId)continue;nodeMarker(ctx,id,moved);}const nodeId=p.selection.nodeId,node=nodeId?model.geometry.nodes[nodeId]:undefined;if(node&&nodeId){const anchor=edit?.nodeIds.has(nodeId)?{x:node.p.x+edit.delta.x,y:node.p.y+edit.delta.y}:node.p,n=toScreen(anchor);for(const id of c?.nodeEdges.get(nodeId)??[]){if(!chosenEdges.current.has(id))continue;const edge=model.geometry.edges[id];if(!edge)continue;edge.segments.forEach((segment,i)=>{for(const key of ['c1','c2']as const){if(edge.nodeIds[key==='c1'?i:i+1]!==nodeId||!segment[key])continue;const point=previewControlPoint(model.geometry,id,i,key,edit)!;const h=toScreen(point);ctx.beginPath();ctx.moveTo(n.x,n.y);ctx.lineTo(h.x,h.y);ctx.strokeStyle='#4772ad';ctx.lineWidth=1;ctx.stroke();ctx.beginPath();ctx.arc(h.x,h.y,3,0,Math.PI*2);ctx.fillStyle='#4772ad';ctx.fill();}});}}}
    // Size overrides are deliberately reapplied over the temporary vector preview.
    if(live&&p.document.kind==='size')for(const pixel of p.document.pixelOverrides){const rgb=p.document.master.palette.entries[pixel.colorIndex].exportRgb;ctx.fillStyle=`rgb(${rgb[0]},${rgb[1]},${rgb[2]})`;ctx.fillRect(v.x+pixel.x*v.zoom,v.y+pixel.y*(d.height/p.render.heightPx)*v.zoom,v.zoom,d.height/p.render.heightPx*v.zoom);}
    if(p.options.overrides)for(const pixel of p.document.pixelOverrides){ctx.strokeStyle='#b52c81';ctx.lineWidth=1.5;ctx.strokeRect(v.x+pixel.x*v.zoom,v.y+pixel.y*(d.height/p.render.heightPx)*v.zoom,v.zoom,d.height/p.render.heightPx*v.zoom);}
    if(drag.current?.kind==='pixel')for(const pixel of drag.current.pixels?.values()??[]){const x=v.x+pixel.x*v.zoom,y=v.y+pixel.y*(d.height/p.render.heightPx)*v.zoom,h=d.height/p.render.heightPx*v.zoom;if(pixel.colorIndex===null){ctx.strokeStyle='#b52c81';ctx.lineWidth=1.5;ctx.strokeRect(x,y,v.zoom,h);}else{const rgb=p.document.master.palette.entries[pixel.colorIndex][p.document.kind==='master'?'displayRgb':'exportRgb'];ctx.fillStyle=`rgb(${rgb[0]},${rgb[1]},${rgb[2]})`;ctx.fillRect(x,y,v.zoom,h);}}
    if(p.document.master.raster&&p.document.kind==='size'){const selecting=drag.current?.kind==='cleanup-area'?drag.current:undefined,area=selecting?cleanupAreaFromDrag(selecting.start,selecting.last,p.document.master.bounds.w,p.document.master.bounds.h):p.document.rules.cleanupRegion;if(area){const x=v.x+area.x*d.width*v.zoom,y=v.y+area.y*d.height*v.zoom,w=area.w*d.width*v.zoom,h=area.h*d.height*v.zoom;ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.strokeRect(x,y,w,h);ctx.strokeStyle='#176a69';ctx.lineWidth=1.5;ctx.setLineDash([6,4]);ctx.strokeRect(x,y,w,h);ctx.setLineDash([]);if(selecting){ctx.fillStyle='#1b8a8520';ctx.fillRect(x,y,w,h);}}}
    if(path.current.length){line(ctx,[...path.current.map(value=>value.p),...(hover.current?[hover.current]:[])],'#a14bcb',2);for(const node of path.current){const s=toScreen(node.p);ctx.fillStyle='#a14bcb';ctx.fillRect(s.x-3,s.y-3,6,6);}}
    ctx.restore();ctx.strokeStyle='#788e7844';ctx.lineWidth=1;ctx.strokeRect(v.x,v.y,d.width*v.zoom,d.height*v.zoom);
    const metrics=(window as unknown as {__JDM_CANVAS_METRICS__?:number[]}).__JDM_CANVAS_METRICS__;if(metrics)metrics.push(performance.now()-started);
  });}
  function nodeMarker(ctx:CanvasRenderingContext2D,id:string,point:Vec2){const p=latest.current,node=p.document.master.geometry.nodes[id];if(!node)return;const at=toScreen(point);ctx.fillStyle=p.selection.nodeId===id?'#d87914':'#fff';ctx.strokeStyle='#315cba';ctx.lineWidth=1.5;ctx.beginPath();node.kind==='smooth'?ctx.arc(at.x,at.y,4,0,Math.PI*2):ctx.rect(at.x-4,at.y-4,8,8);ctx.fill();ctx.stroke();}
  function fit(){const d=dims(),v=view.current;v.zoom=Math.max(.005,Math.min((v.w-64)/d.width,(v.h-64)/d.height));v.x=(v.w-d.width*v.zoom)/2;v.y=(v.h-d.height*v.zoom)/2;latest.current.onZoom(v.zoom);invalidate(true);}
  function zoom(factor:number,at?:Vec2){const v=view.current,q=at??{x:v.w/2,y:v.h/2},next=Math.min(128,Math.max(.005,v.zoom*factor));v.x=q.x-(q.x-v.x)*next/v.zoom;v.y=q.y-(q.y-v.y)*next/v.zoom;v.zoom=next;latest.current.onZoom(next);invalidate(true);}
  function hit(point:Vec2):string|undefined{const p=latest.current,master=displayedMaster(),d=dims(),v=view.current,t=10/(Math.min(d.sx,d.sy)*v.zoom),found=new Set<string>();for(let y=Math.floor((point.y-t)/48);y<=Math.floor((point.y+t)/48);y++)for(let x=Math.floor((point.x-t)/48);x<=Math.floor((point.x+t)/48);x++)for(const id of buckets.current.get(`${x},${y}`)??[])found.add(id);for(const id of changes.current)found.add(id);for(const id of retained.current?.changedEdges??[])found.add(id);for(const id of retained.current?.live?.edgeIds??[])found.add(id);let best:string|undefined,distance=100;const cursor=toScreen(point);for(const id of found){const edge=master.geometry.edges[id];if(!edge||((edge.strokeHidden||owners.current.get(id)?.hidden)&&!p.options.hidden&&id!==p.selection.edgeId))continue;const points=(changes.current.has(id)||retained.current?.changedEdges?.has(id)||retained.current?.live?.edgeIds.has(id))?flattenEdge(edge,master.geometry,.25):p.geometry.paths[id];if(!points)continue;for(let i=1;i<points.length;i++){const a=toScreen(points[i-1]),b=toScreen(points[i]),dx=b.x-a.x,dy=b.y-a.y,k=Math.max(0,Math.min(1,((cursor.x-a.x)*dx+(cursor.y-a.y)*dy)/(dx*dx+dy*dy||1))),q={x:a.x+k*dx,y:a.y+k*dy},dd=sq(cursor,q);if(dd<distance){distance=dd;best=id;}}}return best;}
  function nearestNode(point:Vec2,onlySelected=false):string|undefined{const p=latest.current,master=displayedMaster(),t=transform(),radius=10/Math.min(t.ax,t.ay),ids=cache.current?.nodeIndex.query({minX:point.x-radius,minY:point.y-radius,maxX:point.x+radius,maxY:point.y+radius})??new Set<string>();for(const id of changes.current)for(const nodeId of master.geometry.edges[id]?.nodeIds??[])ids.add(nodeId);for(const id of retained.current?.live?.nodeIds??[])ids.add(id);for(const id of retained.current?.changedEdges??[])for(const nodeId of master.geometry.edges[id]?.nodeIds??[])ids.add(nodeId);const screen=toScreen(point);let best:string|undefined,distance=81;for(const id of ids){if(onlySelected&&!chosenNodes.current.has(id))continue;const node=master.geometry.nodes[id],flags=nodeFlags.current.get(id);if(!node||flags?.locked||(!flags?.visible&&!p.options.hidden))continue;const d=sq(screen,toScreen(node.p));if(d<distance){distance=d;best=id;}}return best;}
  function nearestSegment(edgeId:string,point:Vec2){
    const geometry=latest.current.document.master.geometry,edge=geometry.edges[edgeId],cursor=toScreen(point);let best={segIndex:0,tParam:.5,distance:Infinity};
    edge.segments.forEach((segment,segIndex)=>{const a=geometry.nodes[edge.nodeIds[segIndex]].p,b=geometry.nodes[edge.nodeIds[segIndex+1]].p,curved=!!(segment.c1||segment.c2),c1=segment.c1??a,c2=segment.c2??b;
      const at=(t:number)=>{const u=1-t;return toScreen(curved?{x:u*u*u*a.x+3*u*u*t*c1.x+3*u*t*t*c2.x+t*t*t*b.x,y:u*u*u*a.y+3*u*u*t*c1.y+3*u*t*t*c2.y+t*t*t*b.y}:{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t});};
      const steps=curved?32:1;let distance=Infinity,tParam=.5,previous=at(0);
      for(let i=1;i<=steps;i++){const next=at(i/steps),dx=next.x-previous.x,dy=next.y-previous.y,k=Math.max(0,Math.min(1,((cursor.x-previous.x)*dx+(cursor.y-previous.y)*dy)/(dx*dx+dy*dy||1))),d=sq(cursor,{x:previous.x+k*dx,y:previous.y+k*dy});if(d<distance){distance=d;tParam=(i-1+k)/steps;}previous=next;}
      if(curved){let low=Math.max(0,tParam-1/steps),high=Math.min(1,tParam+1/steps);for(let i=0;i<12;i++){const left=(2*low+high)/3,right=(low+2*high)/3;if(sq(cursor,at(left))<sq(cursor,at(right)))high=right;else low=left;}tParam=(low+high)/2;distance=sq(cursor,at(tParam));}
      if(distance<best.distance)best={segIndex,tParam:Math.max(.001,Math.min(.999,tParam)),distance};
    });return best;
  }
  function finish(close=false){const p=latest.current;if(p.disabled)return;let vertices=path.current;if(vertices.length<2){path.current=[];setDrawing(false);draw();return;}if(close)vertices=[...vertices,{...vertices[0]}];const prefix=`draw-${crypto.randomUUID()}`,nodes:Node[]=[],nodeIds=vertices.map((vertex,i)=>{if(vertex.nodeId)return vertex.nodeId;const id=`${prefix}-n${i}`;nodes.push({id,p:vertex.p,kind:vertex.c?'smooth':'corner'});return id;});if(close)nodeIds[nodeIds.length-1]=nodeIds[0];const segments:BezierSegment[]=vertices.slice(1).map((to,i)=>{const from=vertices[i];return {c1:from.c,c2:to.c?{x:2*to.p.x-to.c.x,y:2*to.p.y-to.c.y}:undefined};});const attached=p.document.master.objects.find(o=>o.edgeIds.some(id=>p.document.master.geometry.edges[id].nodeIds.some(n=>nodeIds.includes(n))));const objectId=attached?.id??`${prefix}-object`;p.onAction({type:'operation',operation:{t:'addEdge',nodes:nodes.filter(n=>nodeIds.includes(n.id)),objectId,objectName:'Drawn motif',edge:{id:prefix,nodeIds,segments,width:3,widthMode:'design',strokeHidden:false,colorIndex:p.color,z:1}}});path.current=[];setDrawing(false);draw();}
  useEffect(()=>{if(cache.current&&cacheGeometry.current?.paths===props.geometry.paths&&cacheGeometry.current?.faces===props.geometry.faces)cache.current.refreshAppearance(renderedMaster);else cache.current=new CanvasGeometryCache(renderedMaster,props.geometry.faces);cacheGeometry.current=props.geometry;preview.current=undefined;changes.current=cache.current.changedEdges(props.document.master.geometry);faceChanges.current=cache.current.changedFaces(props.document.master.geometry);invalidate(true);},[renderedMaster,props.geometry]);
  useEffect(()=>{const p=props;const map=new Map<string,string[]>();for(const[id,points]of Object.entries(p.geometry.paths)){const keys=new Set<string>();for(let i=1;i<points.length;i++)for(let y=Math.floor(Math.min(points[i-1].y,points[i].y)/48);y<=Math.floor(Math.max(points[i-1].y,points[i].y)/48);y++)for(let x=Math.floor(Math.min(points[i-1].x,points[i].x)/48);x<=Math.floor(Math.max(points[i-1].x,points[i].x)/48);x++)keys.add(`${x},${y}`);for(const key of keys){const bucket=map.get(key)??[];bucket.push(id);map.set(key,bucket);}}buckets.current=map;invalidate();},[props.geometry.paths]);
  useEffect(()=>{const edges=new Set<string>(props.selection.edgeId?[props.selection.edgeId]:[]),nodes=new Set<string>(),selected=new Set(props.selection.objectIds);for(const object of props.document.master.objects)if(selected.has(object.id))for(const id of object.edgeIds)edges.add(id);for(const id of edges)for(const nodeId of props.document.master.geometry.edges[id]?.nodeIds??[])nodes.add(nodeId);chosenEdges.current=edges;chosenNodes.current=nodes;invalidate();},[props.selection,props.document.master.objects,props.document.master.geometry.edges]);
  useEffect(()=>{changes.current=cache.current?.changedEdges(props.document.master.geometry)??new Set();faceChanges.current=cache.current?.changedFaces(props.document.master.geometry)??new Set();const held=retained.current;if(held?.live&&held.master){const live=held.live,geometry=props.document.master.geometry,close=(a:Vec2|undefined,b:Vec2)=>!!a&&Math.abs(a.x-b.x)<=1/64&&Math.abs(a.y-b.y)<=1/64;let matched=false;if(live.kind==='node')matched=close(geometry.nodes[live.nodeId!]?.p,held.last);else if(live.kind==='handle')matched=close(geometry.edges[live.edgeId!]?.segments[live.segIndex!]?.[live.key!],held.last);else{const first=live.nodeIds.values().next().value as string|undefined;if(first){const before=held.master.geometry.nodes[first].p;matched=close(geometry.nodes[first]?.p,{x:before.x+live.delta.x,y:before.y+live.delta.y});}}if(matched||(!props.renderPending&&props.document.master===renderedMaster&&renderedMaster!==held.master))retained.current=undefined;}preview.current=undefined;invalidate();},[props.document.master.geometry,props.document.master.palette,props.renderPending]);
  useEffect(()=>{const index=new Map<string,DesignObject>(),flags=new Map<string,{locked:boolean;visible:boolean}>();for(const object of props.document.master.objects)for(const id of object.edgeIds)index.set(id,object);for(const edge of Object.values(props.document.master.geometry.edges)){const owner=index.get(edge.id);for(const id of edge.nodeIds){const old=flags.get(id);flags.set(id,{locked:!!(old?.locked||owner?.locked),visible:!!(old?.visible||(!owner?.hidden&&!edge.strokeHidden))});}}owners.current=index;nodeFlags.current=flags;draw();},[props.document.master.objects,props.document.master.geometry.edges]);
  useEffect(()=>{const r=props.render,c=bitmap.current??document.createElement('canvas');c.width=r.widthPx;c.height=r.heightPx;const bytes=new Uint8ClampedArray(r.grid.length*4),colors=props.document.master.palette.entries.map(entry=>entry[props.document.kind==='master'?'displayRgb':'exportRgb']);for(let i=0,j=0;i<r.grid.length;i++,j+=4){const color=colors[r.grid[i]]??colors[0];bytes[j]=color[0];bytes[j+1]=color[1];bytes[j+2]=color[2];bytes[j+3]=255;}c.getContext('2d')!.putImageData(new ImageData(bytes,c.width,c.height),0,0);bitmap.current=c;invalidate(true);},[props.render.grid,props.render.widthPx,props.render.heightPx,props.document.master.palette,props.document.kind]);
  useEffect(()=>{if(!props.options.changes){changeBitmap.current=undefined;invalidate();return;}const r=props.render,c=changeBitmap.current??document.createElement('canvas');c.width=r.widthPx;c.height=r.heightPx;const bytes=new Uint8ClampedArray(r.widthPx*r.heightPx*4);for(let i=0;i<r.changedPixelsMask.length;i++)if(r.changedPixelsMask[i]){const j=i*4;bytes[j]=255;bytes[j+1]=64;bytes[j+2]=112;bytes[j+3]=112;}c.getContext('2d')!.putImageData(new ImageData(bytes,c.width,c.height),0,0);changeBitmap.current=c;invalidate();},[props.render.changedPixelsMask,props.render.widthPx,props.render.heightPx,props.options.changes]);
  useEffect(()=>{path.current=[];drag.current=undefined;hover.current=undefined;pixelAnchor.current=undefined;setDrawing(false);invalidate();},[props.tool,props.document.id,props.render.widthPx,props.render.heightPx]);
  useEffect(()=>{retained.current=undefined;preview.current=undefined;invalidate(true);},[props.document.id]);
  useEffect(()=>{invalidate(true);},[props.options,props.tool,props.disabled,props.document.pixelOverrides,props.document.rules.cleanupRegion]);
  useEffect(()=>{const command=props.viewCommand,v=view.current,d=dims();if(command.kind==='fit')fit();else if(command.kind==='in')zoom(1.5);else if(command.kind==='out')zoom(1/1.5);else if(command.kind==='actual'){zoom(1/v.zoom);}else if(command.point){v.zoom=Math.max(v.zoom,2);v.x=v.w/2-command.point.x*d.sx*v.zoom;v.y=v.h/2-command.point.y*d.sy*v.zoom;invalidate(true);}},[props.viewCommand]);
  useEffect(()=>{
    let sized=false;const resize=new ResizeObserver(()=>{if(!ref.current||!host.current)return;const v=view.current;v.w=host.current.clientWidth;v.h=host.current.clientHeight;if(!v.w||!v.h)return;const ratio=Math.min(devicePixelRatio||1,2);ref.current.width=v.w*ratio;ref.current.height=v.h*ratio;sized?invalidate(true):fit();sized=true;});resize.observe(host.current!);
    const canvas=ref.current!;const coordinates=(event:PointerEvent|WheelEvent)=>{const rect=canvas.getBoundingClientRect();return{x:event.clientX-rect.left,y:event.clientY-rect.top};};
    const owner=(id:string)=>owners.current.get(id);
    const pixelAt=(point:Vec2)=>{const p=latest.current;return{x:Math.floor(point.x/p.document.master.bounds.w*p.render.widthPx),y:Math.floor(point.y/p.document.master.bounds.h*p.render.heightPx)};};
    const paint=(from:Vec2,to:Vec2,clear:boolean)=>{const p=latest.current,pixels=drag.current?.pixels;if(!pixels)return;pixelLine(from,to,p.render.widthPx,p.render.heightPx,(x,y)=>pixels.set(`${x},${y}`,{x,y,colorIndex:clear?null:p.color}));};
    canvas.onpointerdown=event=>{const p=latest.current,master=displayedMaster(),s=coordinates(event),point=toDesign(s),v=view.current;canvas.focus();if(event.button===1||space.current){drag.current={kind:'pan',start:s,last:s,x:v.x,y:v.y,moved:false};canvas.setPointerCapture(event.pointerId);return;}if(p.disabled||event.button!==0||!toolAvailable(p.tool,p.document))return;
      if(p.tool==='zoom'){zoom(event.altKey?1/1.5:1.5,s);return;}if(p.tool==='fill'){p.onFill(point,event.altKey);return;}
      if(p.tool==='line'||p.tool==='pen'){if(path.current.length>2&&sq(s,toScreen(path.current[0].p))<100){finish(true);return;}const snapped=nearestNode(point);let at=snapped?master.geometry.nodes[snapped].p:point;if(event.shiftKey&&path.current.length&&!snapped){const last=path.current.at(-1)!.p,angle=Math.round(Math.atan2(at.y-last.y,at.x-last.x)/(Math.PI/4))*Math.PI/4,length=Math.sqrt(sq(at,last));at={x:last.x+Math.cos(angle)*length,y:last.y+Math.sin(angle)*length};}path.current.push({p:at,nodeId:snapped});setDrawing(true);drag.current={kind:'draw',start:point,last:at,original:at,x:0,y:0,moved:false};canvas.setPointerCapture(event.pointerId);draw();return;}
      if(p.tool==='cleanup-area'){const {w,h}=p.document.master.bounds;if(point.x<0||point.y<0||point.x>w||point.y>h)return;drag.current={kind:'cleanup-area',start:point,last:point,x:0,y:0,moved:false};canvas.setPointerCapture(event.pointerId);draw();return;}
      if(p.tool==='pixel'){if(p.document.kind!=='size')return;const pixel=pixelAt(point);drag.current={kind:'pixel',start:point,last:point,x:0,y:0,moved:false,pixels:new Map()};paint(event.shiftKey&&pixelAnchor.current?pixelAnchor.current:pixel,pixel,event.altKey);canvas.setPointerCapture(event.pointerId);draw();return;}
      const edgeId=hit(point);if(p.tool==='node'){
        const nodeId=nearestNode(point,true),onAnchor=!!nodeId&&sq(s,toScreen(master.geometry.nodes[nodeId].p))<25;
        if(!onAnchor)for(const id of cache.current?.nodeEdges.get(p.selection.nodeId??'')??[]){if(!chosenEdges.current.has(id))continue;const edge=master.geometry.edges[id];if(!edge||owner(id)?.locked)continue;for(let i=0;i<edge.segments.length;i++)for(const key of ['c1','c2']as const){const handle=edge.segments[i][key],nodeId=edge.nodeIds[key==='c1'?i:i+1];if(handle&&!nodeFlags.current.get(nodeId)?.locked&&nodeId===p.selection.nodeId&&sq(s,toScreen(handle))<64){drag.current={kind:'handle',start:point,last:handle,original:handle,x:0,y:0,moved:false,edgeId:id,segIndex:i,key};beginLive(drag.current);canvas.setPointerCapture(event.pointerId);draw();return;}}}
        if(nodeId){p.onSelect({...p.selection,nodeId});if(event.altKey){p.onAction({type:'operation',operation:{t:'setNodeKind',nodeId,kind:master.geometry.nodes[nodeId].kind==='corner'?'smooth':'corner'}});return;}const original=master.geometry.nodes[nodeId].p;drag.current={kind:'node',nodeId,start:point,last:original,original,x:0,y:0,moved:false};beginLive(drag.current);canvas.setPointerCapture(event.pointerId);draw();return;}
      }
      if(!edgeId){p.onSelect({objectIds:[]});return;}const object=owner(edgeId);if(p.tool==='erase'){if(!object?.locked)p.onAction({type:'operation',operation:{t:'deleteEdge',edgeId}});return;}
      const objectIds=event.shiftKey?([...new Set([...p.selection.objectIds,...(object?[object.id]:[])])]):object?[object.id]:[];p.onSelect({edgeId,objectIds});if(p.tool==='select'&&objectIds.length&&!master.objects.some(item=>item.locked&&objectIds.includes(item.id))){drag.current={kind:'object',start:point,last:point,x:0,y:0,moved:false,objectIds};beginLive(drag.current);canvas.setPointerCapture(event.pointerId);draw();}
    };
    canvas.onpointermove=event=>{const s=coordinates(event),point=toDesign(s),dr=drag.current;hover.current=point;if(!dr){if(path.current.length)draw();return;}if(dr.kind==='pan'){if(sq(s,dr.start)>16)dr.moved=true;view.current.x=dr.x+s.x-dr.start.x;view.current.y=dr.y+s.y-dr.start.y;sceneDirty.current=true;overlayDirty.current=true;}else{dr.moved||=sq(toScreen(dr.start),s)>16;if(dr.kind==='pixel')paint(pixelAt(dr.last),pixelAt(point),event.altKey);dr.last=dr.original?{x:dr.original.x+point.x-dr.start.x,y:dr.original.y+point.y-dr.start.y}:point;if(dr.live){const origin=dr.original??dr.start;dr.live.delta={x:dr.last.x-origin.x,y:dr.last.y-origin.y};}if(dr.kind==='draw'&&latest.current.tool==='pen'&&dr.moved&&path.current.length)path.current.at(-1)!.c=dr.last;}draw();};
    canvas.onpointerup=event=>{const dr=drag.current,p=latest.current;if(!dr)return;drag.current=undefined;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);if(p.disabled){invalidate();return;}if(dr.live&&dr.moved)retained.current=dr;else if(dr.live){preview.current=undefined;overlayDirty.current=true;}if(dr.kind==='node'&&dr.moved)p.onAction({type:'operation',operation:{t:'moveNodes',nodes:[{id:dr.nodeId!,to:dr.last}]}});if(dr.kind==='handle'&&dr.moved){const segment=(dr.master??p.document.master).geometry.edges[dr.edgeId!]?.segments[dr.segIndex!];if(segment)p.onAction({type:'operation',operation:{t:'setControls',edgeId:dr.edgeId!,segIndex:dr.segIndex!,...segment,[dr.key!]:dr.last}});}if(dr.kind==='object'&&dr.moved&&dr.objectIds?.length)p.onAction({type:'operation',operation:{t:'transformObjects',objectIds:dr.objectIds,matrix:[1,0,0,1,dr.last.x-dr.start.x,dr.last.y-dr.start.y]}});if(dr.kind==='cleanup-area'&&dr.moved){const area=cleanupAreaFromDrag(dr.start,dr.last,p.document.master.bounds.w,p.document.master.bounds.h);if(area){p.onAction({type:'rules',rules:{...p.document.rules,cleanupRegion:area}});p.onCleanupAreaDone?.();}}
      if(dr.kind==='pixel'&&dr.pixels?.size){pixelAnchor.current=pixelAt(dr.last);p.onAction({type:'pixels',pixels:[...dr.pixels.values()]});}draw();};
    canvas.onpointercancel=()=>{drag.current=undefined;preview.current=undefined;invalidate();};
    canvas.ondblclick=event=>{const p=latest.current;if(p.disabled)return;if(p.tool==='line'||p.tool==='pen'){if(path.current.length>1&&sq(path.current.at(-1)!.p,path.current.at(-2)!.p)<.01)path.current.pop();finish();}else if(p.tool==='node'){const point=toDesign(coordinates(event as unknown as PointerEvent)),edgeId=hit(point);if(!edgeId||owner(edgeId)?.locked||nearestNode(point,true))return;const nearest=nearestSegment(edgeId,point);p.onAction({type:'operation',operation:{t:'insertNode',edgeId,segIndex:nearest.segIndex,tParam:nearest.tParam,nodeId:`node-${crypto.randomUUID()}`}});}};
    const wheel=(event:WheelEvent)=>{event.preventDefault();zoom(Math.exp(-event.deltaY*.0015),coordinates(event));};canvas.addEventListener('wheel',wheel,{passive:false});
    const key=(event:KeyboardEvent)=>{if(event.code==='Space')space.current=event.type==='keydown';if(event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement||event.target instanceof HTMLSelectElement||((event.target as HTMLElement)?.isContentEditable))return;if(event.code==='Space'){space.current=event.type==='keydown';event.preventDefault();}if(event.type==='keydown'&&event.key==='Enter'&&path.current.length){event.preventDefault();finish();}if(event.type==='keydown'&&event.key==='Escape'){path.current=[];drag.current=undefined;preview.current=undefined;setDrawing(false);invalidate();if(latest.current.tool==='cleanup-area')latest.current.onCleanupAreaDone?.();}};
    const blur=()=>{space.current=false;drag.current=undefined;preview.current=undefined;invalidate();};window.addEventListener('keydown',key);window.addEventListener('keyup',key);window.addEventListener('blur',blur);
    return()=>{resize.disconnect();canvas.removeEventListener('wheel',wheel);window.removeEventListener('keydown',key);window.removeEventListener('keyup',key);window.removeEventListener('blur',blur);cancelAnimationFrame(frame.current);};
  },[]);
  return <div ref={host} className="canvas-host"><canvas ref={ref} tabIndex={0} aria-label="Design canvas"/><div className="canvas-hint">{drawing?'Enter to finish · click start to close · Esc to cancel':props.tool==='cleanup-area'?'Drag a rectangle for cleanup · Esc cancels · Space + drag to pan':props.tool==='pixel'?'Shift + click for a straight pixel line · Alt clears overrides':'Scroll to zoom · Space + drag to pan'}{props.document.kind==='master'?' · Master preview':''}</div>{props.disabled&&<div className="canvas-busy">Updating design…</div>}</div>;
}


