import {useEffect,useMemo,useRef,useState} from 'react';
import type {DesignRecord,DesignSummary,EditorAction,VersionSummary,ExportSummary,WorkspaceSettings} from '../../../packages/app-model/src/index';
import {resolveSize} from '../../../packages/core/src/size';
import type {Palette,SizeInput,Vec2,Master} from '../../../packages/core/src/types';
import type {Operation} from '../../../packages/core/src/ops';
import {api,clientId,downloadBytes} from './api';
import {useEditor} from './useEditor';
import DesignCanvas,{type Tool,type Selection,type ViewOptions} from './DesignCanvas';
import Compare from './VersionCompare';

const tools:{id:Tool;key:string;label:string;icon:string}[]=[{id:'select',key:'V',label:'Select / move',icon:'↖'},{id:'node',key:'A',label:'Nodes / handles',icon:'◇'},{id:'pen',key:'P',label:'Pen',icon:'✒'},{id:'line',key:'L',label:'Line',icon:'╱'},{id:'fill',key:'K',label:'Fill',icon:'▰'},{id:'erase',key:'E',label:'Erase edge',icon:'⌫'},{id:'pixel',key:'B',label:'Pixel pencil',icon:'▪'},{id:'zoom',key:'Z',label:'Zoom',icon:'⌕'}];
interface Props{initial:DesignRecord;settings:WorkspaceSettings;onBack:()=>void;onOpen:(id:string)=>void;onReload:()=>Promise<void>}
export default function Editor({initial,settings,onBack,onOpen,onReload}:Props){
  const engine=useEditor(initial,settings),doc=engine.interactiveDocument??engine.state?.document??initial;
  const [tool,setTool]=useState<Tool>('select'),[color,setColor]=useState(1),[selection,setSelection]=useState<Selection>({objectIds:[]}),[tab,setTab]=useState<'design'|'objects'|'output'|'history'>('design'),[zoom,setZoom]=useState(1),[viewCommand,setViewCommand]=useState<{kind:'fit'|'actual'|'in'|'out'|'focus';serial:number;point?:Vec2}>({kind:'fit',serial:0});
  const [options,setOptions]=useState<ViewOptions>({boundaries:true,nodes:false,repeat:false,trueProportion:true,grid:false,changes:false,overrides:false,hidden:false}),[versions,setVersions]=useState<VersionSummary[]>([]),[exports,setExports]=useState<ExportSummary[]>([]),[siblings,setSiblings]=useState<DesignSummary[]>([]),[note,setNote]=useState(''),[name,setName]=useState(doc.name),[tags,setTags]=useState(doc.tags.join(', ')),[objectFilter,setObjectFilter]=useState(''),[paletteDraft,setPaletteDraft]=useState<Palette>(),[mergeTarget,setMergeTarget]=useState(0),[notice,setNotice]=useState(''),[savingVersion,setSavingVersion]=useState(false),[exporting,setExporting]=useState(false),[comparison,setComparison]=useState<{document:DesignRecord;title:string;rebase?:boolean;sourceSequence?:number;warnings?:string[]}>();
  const [sizeMode,setSizeMode]=useState<'grid'|'in'|'cm'|'fit'>('grid'),[width,setWidth]=useState('1200'),[height,setHeight]=useState(''),[linked,setLinked]=useState(true),[profileId,setProfileId]=useState(doc.profileId),[newName,setNewName]=useState(''),[across,setAcross]=useState('2'),[styleWidth,setStyleWidth]=useState('3');
  const live=useRef({engine,doc,tool,selection,color,exporting});live.current={engine,doc,tool,selection,color,exporting};
  const [recordMutation,setRecordMutation]=useState(false);
  const disabled=engine.busy||engine.readOnly||savingVersion||recordMutation;
  const edge=selection.edgeId?doc.master.geometry.edges[selection.edgeId]:undefined;
  const profile=settings.profiles.find(p=>p.id===profileId)??settings.profiles[0];
  const action=(value:EditorAction)=>{if(!disabled)void engine.action(value);},op=(operation:Operation)=>action({type:'operation',operation});
  const view=(kind:'fit'|'actual'|'in'|'out'|'focus',point?:Vec2)=>setViewCommand(old=>({kind,point,serial:old.serial+1}));
  const sizeInput:SizeInput=sizeMode==='fit'?{mode:'fitAcross',n:Number(across)}:sizeMode==='grid'?{mode:'grid',widthPx:width?Number(width):undefined,heightPx:!linked&&height?Number(height):undefined,linkAspect:linked}:{mode:'physical',unit:sizeMode,width:width?Number(width):undefined,height:!linked&&height?Number(height):undefined,linkAspect:linked};
  const resolved=useMemo(()=>{try{return {value:resolveSize(doc.master.bounds,profile,sizeInput),error:''};}catch(e){return {value:undefined,error:(e as Error).message};}},[doc.master.bounds,profile,JSON.stringify(sizeInput)]);
  useEffect(()=>{setName(doc.name);setTags(doc.tags.join(', '));},[doc.name,doc.tags.join(',')]);
  useEffect(()=>{setProfileId(doc.profileId);const s=doc.sizeInput;if(s.mode==='grid'){setSizeMode('grid');setWidth(String(s.widthPx??''));setHeight(String(s.heightPx??''));setLinked(s.linkAspect);}else if(s.mode==='physical'){setSizeMode(s.unit);setWidth(String(s.width??''));setHeight(String(s.height??''));setLinked(s.linkAspect);}else{setSizeMode('fit');setAcross(String(s.n));}},[JSON.stringify(doc.sizeInput),doc.profileId]);
  useEffect(()=>{if(edge)setStyleWidth(String(edge.width));},[edge?.id,edge?.width]);
  useEffect(()=>{void refreshHistory();void api<DesignSummary[]>('/designs').then(setSiblings).catch(()=>{});},[initial.id]);
  useEffect(()=>{if(color>=doc.master.palette.entries.length)setColor(0);const objectIds=selection.objectIds.filter(id=>doc.master.objects.some(o=>o.id===id));if(objectIds.length!==selection.objectIds.length||(selection.edgeId&&!doc.master.geometry.edges[selection.edgeId]))setSelection({objectIds});},[doc.master]);
  async function refreshHistory(){try{const [v,e]=await Promise.all([api<VersionSummary[]>(`/designs/${initial.id}/versions`),api<ExportSummary[]>(`/designs/${initial.id}/exports`)]);setVersions(v);setExports(e);}catch(error){engine.setError((error as Error).message);}}
  async function saveVersion(){if(disabled)return;setSavingVersion(true);try{const saved=await engine.save();const result=await api<{document:DesignRecord;version:VersionSummary}>(`/designs/${doc.id}/versions`,{note:note.trim()||'Design checkpoint',expectedRevision:saved.revision,clientId});engine.acceptServer(result.document);setNote('');setNotice(`Version ${result.version.version} saved`);await refreshHistory();}catch(e){engine.setError((e as Error).message);}finally{setSavingVersion(false);}}
  async function createSize(){if(!resolved.value||disabled)return;setRecordMutation(true);try{await engine.save();const parent=doc.kind==='size'?doc.masterId!:doc.id;const result=await api<DesignRecord>(`/designs/${parent}/variants`,{name:newName.trim()||`${resolved.value.widthPx} × ${resolved.value.heightPx}`,profileId,sizeInput});onOpen(result.id);}catch(e){engine.setError((e as Error).message);}finally{setRecordMutation(false);}}
  async function exportDesign(){if(disabled||exporting||doc.kind!=='size')return;setExporting(true);setNotice('Preparing indexed export…');try{const saved=await engine.save();const result=await api<ExportSummary>(`/designs/${doc.id}/exports`,{expectedRevision:saved.revision,clientId});setExports(old=>[result,...old]);setNotice(`Export ready · ${result.widthPx} × ${result.heightPx}`);const anchor=document.createElement('a');anchor.href=`/api/designs/${doc.id}/exports/${result.id}/bmp`;anchor.download=result.filename;anchor.click();}catch(e){engine.setError((e as Error).message);}finally{setExporting(false);}}
  async function restore(id:string){if(disabled)return;setRecordMutation(true);try{const saved=await engine.save();await api(`/designs/${doc.id}/restore`,{versionId:id,expectedRevision:saved.revision,clientId});await onReload();}catch(e){engine.setError((e as Error).message);}finally{setRecordMutation(false);}}
  async function compareVersion(id:string,title:string){try{const previous=await api<DesignRecord>(`/designs/${doc.id}/versions/${id}`);setComparison({document:previous,title});}catch(e){engine.setError((e as Error).message);}}
  async function rebase(){if(!doc.masterId||disabled)return;const sourceSequence=engine.state?.editSequence;setRecordMutation(true);setNotice('Checking this size against the current master…');try{await engine.save();const parent=await api<DesignRecord>(`/designs/${doc.masterId}`);const w=new Worker(new URL('./rebase.worker.ts',import.meta.url),{type:'module'});const result=await new Promise<{document:DesignRecord;warnings:string[]}>((resolve,reject)=>{w.onmessage=({data})=>{w.terminate();data.error?reject(new Error(data.error)):resolve(data);};w.onerror=e=>{w.terminate();reject(new Error(e.message));};w.postMessage({variant:engine.getDocument(),parent:parent.master});});setComparison({document:result.document,title:`Updated from master v${parent.master.version}`,rebase:true,sourceSequence,warnings:result.warnings});setNotice('Review the update before keeping it.');}catch(e){engine.setError((e as Error).message);}finally{setRecordMutation(false);}}
  async function fill(point:Vec2,pick:boolean){if(disabled)return;try{const found=await engine.hitFace(point);if(found?.faceId){if(pick)setColor(found.colorIndex??0);else op({t:'setFaceColor',faceId:found.faceId,ref:found.ref??point,colorIndex:color});}}catch(e){engine.setError((e as Error).message);}}
  function selectionCenter():Vec2|undefined {
    let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;
    for(const object of doc.master.objects)if(selection.objectIds.includes(object.id))for(const id of object.edgeIds)for(const nodeId of doc.master.geometry.edges[id]?.nodeIds??[]){const p=doc.master.geometry.nodes[nodeId].p;minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y);}
    return Number.isFinite(minX)?{x:(minX+maxX)/2,y:(minY+maxY)/2}:undefined;
  }
  function transform(scale:number,flip=false){const center=selectionCenter();if(!center)return;const {x:cx,y:cy}=center;op({t:'transformObjects',objectIds:selection.objectIds,matrix:[flip?-1:scale,0,0,scale,flip?2*cx:cx*(1-scale),cy*(1-scale)]});}
  function rotate(){const center=selectionCenter();if(!center)return;const {x:cx,y:cy}=center;op({t:'transformObjects',objectIds:selection.objectIds,matrix:[0,1,-1,0,cx+cy,cy-cx]});}
  function navigate(next:()=>void){if(engine.readOnly){next();return;}void engine.save().then(next).catch(e=>engine.setError(e.message));}
  useEffect(()=>{
    if(!engine.state||engine.readOnly)return;const render=engine.state.render,renderDoc=engine.renderedDocument??engine.state.document;
    const timer=setTimeout(()=>{
      const scale=Math.min(240/render.widthIn,240/render.heightIn),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(render.widthIn*scale));canvas.height=Math.max(1,Math.round(render.heightIn*scale));
      const rgba=new Uint8ClampedArray(canvas.width*canvas.height*4);
      for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const color=renderDoc.master.palette.entries[render.grid[Math.floor(y*render.heightPx/canvas.height)*render.widthPx+Math.floor(x*render.widthPx/canvas.width)]].displayRgb,i=(y*canvas.width+x)*4;rgba[i]=color[0];rgba[i+1]=color[1];rgba[i+2]=color[2];rgba[i+3]=255;}
      canvas.getContext('2d')!.putImageData(new ImageData(rgba,canvas.width,canvas.height),0,0);
      canvas.toBlob(blob=>{if(blob)void fetch('/api/designs/'+doc.id+'/thumbnail',{method:'PUT',headers:{'Content-Type':'image/png','x-jdm-client-id':clientId},body:blob}).catch(()=>{});},'image/png');
    },1500);return()=>clearTimeout(timer);
  },[engine.state?.render,engine.readOnly]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement||event.target instanceof HTMLSelectElement)return;const value=live.current;if(event.ctrlKey||event.metaKey){const lower=event.key.toLowerCase();if(['z','s','e','a','d','g','j','0','1'].includes(lower))event.preventDefault();if(lower==='z'&&!disabled)void value.engine.history(event.shiftKey?'redo':'undo');if(lower==='s')void saveVersion();if(lower==='e')void exportDesign();if(lower==='0')view('fit');if(lower==='1')view('actual');if(lower==='d')setSelection({objectIds:[]});if(lower==='a')setSelection({objectIds:value.doc.master.objects.filter(o=>!o.locked&&!o.hidden).map(o=>o.id)});if(lower==='j'&&value.selection.objectIds.length)action({type:'operation',operation:{t:'duplicateObjects',objectIds:value.selection.objectIds,offset:{x:10,y:10},idPrefix:`copy-${crypto.randomUUID()}`}});if(lower==='g'&&value.selection.objectIds.length)action({type:'operation',operation:event.shiftKey?{t:'ungroup',objectId:value.selection.objectIds[0]}:{t:'group',objectIds:value.selection.objectIds,resultId:`group-${crypto.randomUUID()}`,name:'Group'}});return;}const chosen=tools.find(t=>t.key.toLowerCase()===event.key.toLowerCase()||(event.key.toLowerCase()==='g'&&t.id==='fill'));if(chosen&&!(chosen.id==='pixel'&&value.doc.kind!=='size'))setTool(chosen.id);if(event.key==='Escape')setSelection({objectIds:[]});if(/^[0-5]$/.test(event.key))setColor(Math.min(Number(event.key),value.doc.master.palette.entries.length-1));if(event.key==='['||event.key===']')setColor(c=>(c+(event.key===']'?1:value.doc.master.palette.entries.length-1))%value.doc.master.palette.entries.length);if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();if(value.selection.nodeId&&value.selection.edgeId&&value.tool==='node')action({type:'operation',operation:{t:'deleteNode',edgeId:value.selection.edgeId,nodeId:value.selection.nodeId}});else if(value.selection.edgeId)action({type:'operation',operation:{t:'setStrokeVisibility',edgeIds:[value.selection.edgeId],hidden:true}});}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[disabled,doc.revision,selection,tool,color]);
  const family=siblings.filter(s=>s.id===(doc.masterId??doc.id)||s.masterId===(doc.masterId??doc.id));
  return <div className="editor-app"><header className="editor-header"><button className="editor-back" title="Back to library" disabled={engine.busy||savingVersion||recordMutation} onClick={()=>navigate(onBack)}>‹ <span>Library</span></button><div className="document-title"><strong>{doc.name}</strong><span>{doc.kind==='master'?'MASTER':`SIZE · MASTER v${doc.baseMasterVersion??1}`} · v{doc.master.version}</span></div><div className="mode-switch"><select aria-label="Master or size" value={doc.id} onChange={e=>{const id=e.target.value;navigate(()=>onOpen(id));}} disabled={engine.busy||savingVersion||recordMutation}>{family.length?family.map(s=><option value={s.id} key={s.id}>{s.kind==='master'?'Master':s.name}</option>):<option value={doc.id}>{doc.kind==='master'?'Master':doc.name}</option>}</select><button onClick={()=>setTab('output')}>+ New size</button></div><div className="header-spacer"/><span className="save-indicator" title={engine.saveStatus}><i className={engine.saveStatus.startsWith('Saved on')?'saved':''}/>{engine.saveStatus}</span><button onClick={()=>{setTab('history');void saveVersion();}} disabled={disabled||savingVersion}>Save version</button><button className="primary" onClick={()=>doc.kind==='master'?setTab('output'):void exportDesign()} disabled={disabled||exporting}>{exporting?'Exporting…':doc.kind==='master'?'Create size':'Export BMP ↗'}</button></header>
    <div className="editor-topbar"><button disabled={disabled||!engine.state?.canUndo} onClick={()=>void engine.history('undo')} title="Undo (Ctrl+Z)">↶</button><button disabled={disabled||!engine.state?.canRedo} onClick={()=>void engine.history('redo')} title="Redo (Ctrl+Shift+Z)">↷</button><span className="separator"/><button onClick={()=>view('fit')}>Fit</button><button onClick={()=>view('actual')}>100%</button><button onClick={()=>view('out')}>−</button><span className="zoom-number">{Math.round(zoom*100)}%</span><button onClick={()=>view('in')}>+</button><span className="separator"/>{([['boundaries','Boundaries'],['nodes','Nodes'],['hidden','Hidden strokes'],['repeat','Repeat'],['trueProportion','True proportion'],['grid','Pixel grid'],['changes','Cleanup'],['overrides','Overrides']]as const).map(([id,label])=><label key={id}><input type="checkbox" checked={options[id]} onChange={e=>setOptions(old=>({...old,[id]:e.target.checked}))}/>{label}</label>)}</div>
    {(engine.error||notice||engine.readOnly)&&<div className={engine.error?'message error':'message'} role={engine.error?'alert':'status'}><span>{engine.error||notice||'This design is read-only in this tab.'}</span>{engine.error&&<>{!engine.readOnly&&<button disabled={engine.busy} onClick={()=>void engine.save().then(()=>engine.setError('')).catch(e=>engine.setError(e.message))}>Retry save</button>}<button onClick={()=>engine.setError('')}>Dismiss</button></>}{engine.conflict&&<><button onClick={()=>downloadBytes(new TextEncoder().encode(JSON.stringify(engine.conflict)),'jdm-recovery.json','application/json')}>Download recovery</button><button onClick={()=>void engine.discardRecovery()}>Discard local draft</button></>}</div>}
    <div className="editor-body"><aside className="tool-rail">{tools.map(item=><button key={item.id} aria-label={item.label} title={`${item.label} (${item.key})`} className={tool===item.id?'selected':''} disabled={item.id==='pixel'&&doc.kind!=='size'} onClick={()=>setTool(item.id)}><span>{item.icon}</span><small>{item.key}</small></button>)}<div className="active-ink" style={{background:`rgb(${doc.master.palette.entries[color]?.displayRgb.join(',')})`}} title={`Color ${color}`}/></aside>
      {comparison&&engine.state?<div className="comparison-workspace"><div className="comparison-heading"><strong>{comparison.title}</strong><button onClick={()=>setComparison(undefined)}>Close comparison</button>{comparison.rebase&&<button className="primary" disabled={disabled} onClick={()=>{if(comparison.sourceSequence!==engine.state?.editSequence){void rebase();return;}action({type:'replace',master:comparison.document.master,operations:comparison.document.operations,baseMasterVersion:comparison.document.baseMasterVersion});setComparison(undefined);}}>{comparison.sourceSequence===engine.state?.editSequence?'Keep updated size':'Review latest edits'}</button>}</div>{comparison.warnings?.length?<div className="message">{comparison.warnings.join(' ')}</div>:null}<Compare previous={comparison.document} current={engine.state} settings={settings} previousLabel={comparison.rebase?'Proposed updated size':'Selected version'}/></div>:engine.state&&engine.geometry?<DesignCanvas document={doc} renderedDocument={engine.renderedDocument} renderPending={engine.renderPending} geometry={engine.geometry} render={engine.state.render} tool={tool} color={color} selection={selection} onSelect={setSelection} onAction={action} onFill={fill} options={options} viewCommand={viewCommand} disabled={disabled} onZoom={setZoom}/>:<div className="canvas-loading"><div className="spinner"/><h2>Preparing your design</h2><p>Building editable regions and the pixel preview.</p></div>}
      <aside className="inspector"><div className="inspector-tabs">{(['design','objects','output','history']as const).map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?'active':''}>{t}</button>)}</div>
        {tab==='design'&&<><section><div className="section-heading"><h2>Palette <span>{doc.master.palette.entries.length} / 6</span></h2><button className="text-button" onClick={()=>setPaletteDraft(structuredClone(doc.master.palette))}>Edit</button></div><div className="palette-grid">{doc.master.palette.entries.map(entry=><button key={entry.index} className={color===entry.index?'active':''} onClick={()=>setColor(entry.index)} onDoubleClick={()=>setPaletteDraft(structuredClone(doc.master.palette))}><span style={{background:`rgb(${entry.displayRgb.join(',')})`}}/><small>{entry.index} · {entry.name}</small></button>)}</div><p className="muted">Choose a color, then use Fill (K) on a region.</p>{!!engine.state?.render.report.unassignedFaces&&<p className="warning-text">{engine.state.render.report.unassignedFaces.toLocaleString()} regions still need a color. Unassigned regions export as ground.</p>}{color>0&&!paletteDraft&&<details className="palette-merge"><summary>Merge selected color…</summary><label className="field">Replace color {color} with<select aria-label="Merge into color" value={mergeTarget===color?0:mergeTarget} onChange={e=>setMergeTarget(Number(e.target.value))}>{doc.master.palette.entries.filter(e=>e.index!==color).map(e=><option key={e.index} value={e.index}>{e.index} · {e.name}</option>)}</select></label><button disabled={disabled} onClick={()=>{op({t:'mergePalette',sourceIndex:color,targetIndex:mergeTarget===color?0:mergeTarget});setMergeTarget(0);setColor(0);}}>Merge and remove color {color}</button><p className="muted">Updates fills, strokes and pixel corrections. Undo restores the palette.</p></details>}{paletteDraft&&<div className="inline-editor"><h3>Edit palette</h3><p className="muted">Name · display color · BMP color</p>{paletteDraft.entries.map((entry,i)=><div className="palette-row" key={i}><input aria-label={`Color ${i} name`} value={entry.name} onChange={e=>setPaletteDraft(p=>p?{entries:p.entries.map((v,n)=>n===i?{...v,name:e.target.value}:v)}:p)}/>{(['displayRgb','exportRgb']as const).map(key=><input key={key} type="color" title={key==='displayRgb'?'Display color':'Export color'} value={'#'+entry[key].map(v=>v.toString(16).padStart(2,'0')).join('')} onChange={e=>{const hex=e.target.value;setPaletteDraft(p=>p?{entries:p.entries.map((v,n)=>n===i?{...v,[key]:[1,3,5].map(k=>parseInt(hex.slice(k,k+2),16))}:v)}:p);}}/>)}</div>)}<div className="button-row">{paletteDraft.entries.length<6&&<button onClick={()=>setPaletteDraft(p=>p?{entries:[...p.entries,{index:p.entries.length,name:'Color '+p.entries.length,displayRgb:[120,120,120],exportRgb:[120,120,120]}]}:p)}>Add color</button>}<button disabled={disabled} onClick={()=>{op({t:'setPalette',palette:paletteDraft});setPaletteDraft(undefined);}}>Apply colors</button><button onClick={()=>setPaletteDraft(undefined)}>Cancel</button></div></div>}</section>
          <section><h2>Selected stroke</h2>{edge?<><p className="selected-label">{edge.strokeHidden?'Hidden':'Visible'} <span>{edge.id}</span></p><div className="button-row"><button className="primary" disabled={disabled} onClick={()=>op({t:'setStrokeVisibility',edgeIds:[edge.id],hidden:!edge.strokeHidden})}>{edge.strokeHidden?'Restore stroke':'Hide stroke'}</button><button disabled={disabled} onClick={()=>op({t:'setEdgeStyle',edgeId:edge.id,width:edge.width,colorIndex:color})}>Use color {color}</button></div><label className="field">Stroke width <span className="field-suffix">{edge.widthMode==='design'?'source units':'output px'}</span><input type="number" min="0" step="0.25" disabled={disabled} value={styleWidth} onChange={e=>setStyleWidth(e.target.value)} onBlur={()=>{const n=Number(styleWidth);if(Number.isFinite(n)&&n>=0&&n!==edge.width)op({t:'setEdgeStyle',edgeId:edge.id,width:n});}}/></label><p className="muted">Hiding keeps the fill boundaries and original width.</p><button className="danger-link" disabled={disabled} onClick={()=>{if(confirm('Delete this boundary? Adjacent regions may merge. You can undo this edit.'))op({t:'deleteEdge',edgeId:edge.id});}}>Delete boundary</button></>:<p className="muted">Select a line to hide it, restore it or change its style.</p>}</section>
          <section><h2>Design details</h2><label className="field">Name<input disabled={disabled} value={name} onChange={e=>setName(e.target.value)} onBlur={()=>{if(name.trim()!==doc.name)action({type:'metadata',name:name.trim()||doc.name,tags:doc.tags});}}/></label><label className="field">Tags<input placeholder="Floral, border, pallu…" disabled={disabled} value={tags} onChange={e=>setTags(e.target.value)} onBlur={()=>{const next=tags.split(',').map(s=>s.trim()).filter(Boolean);if(JSON.stringify(next)!==JSON.stringify(doc.tags))action({type:'metadata',name:doc.name,tags:next});}}/></label><button onClick={()=>downloadBytes(new TextEncoder().encode(JSON.stringify(engine.getDocument().master,null,2)),doc.name.replace(/[^a-zA-Z0-9_-]+/g,'-')+'-master.json','application/json')} disabled={engine.busy}>Download master JSON</button></section>
          <section><h2>Hidden strokes</h2><div className="scroll-list">{Object.values(doc.master.geometry.edges).filter(e=>e.strokeHidden).slice(0,100).map(e=><button key={e.id} onClick={()=>{setSelection({edgeId:e.id,objectIds:[]});const p=doc.master.geometry.nodes[e.nodeIds[0]].p;view('focus',p);}}>{e.id} <span>Find →</span></button>)}</div><p className="muted">Use “Hidden strokes” above to see hidden lines.</p></section></>}
        {tab==='objects'&&<><section><h2>Motifs & objects <span>{doc.master.objects.length}</span></h2><input className="search-field" placeholder="Find an object…" value={objectFilter} onChange={e=>setObjectFilter(e.target.value)}/><div className="object-actions"><button disabled={disabled||selection.objectIds.length<2} onClick={()=>op({t:'group',objectIds:selection.objectIds,resultId:`group-${crypto.randomUUID()}`,name:'Group'})}>Group</button><button disabled={disabled||selection.objectIds.length!==1} onClick={()=>op({t:'ungroup',objectId:selection.objectIds[0]})}>Ungroup</button><button disabled={disabled||!selection.objectIds.length} onClick={()=>op({t:'duplicateObjects',objectIds:selection.objectIds,offset:{x:10,y:10},idPrefix:`copy-${crypto.randomUUID()}`})}>Duplicate</button><button disabled={disabled||!selection.objectIds.length} onClick={()=>{if(confirm('Delete the selected objects? You can undo this edit.'))op({t:'deleteObjects',objectIds:selection.objectIds});}}>Delete</button><button disabled={disabled||!selection.objectIds.length} onClick={()=>transform(1.1)}>Scale +10%</button><button disabled={disabled||!selection.objectIds.length} onClick={()=>transform(.9)}>Scale −10%</button><button disabled={disabled||!selection.objectIds.length} onClick={()=>transform(1,true)}>Flip</button><button disabled={disabled||!selection.objectIds.length} onClick={rotate}>Rotate 90°</button></div><div className="object-list">{doc.master.objects.filter(o=>o.name.toLowerCase().includes(objectFilter.toLowerCase())||o.id.includes(objectFilter)).slice(0,180).map(object=><div key={object.id} className={selection.objectIds.includes(object.id)?'active':''}><button className="object-name" onClick={e=>{setSelection({objectIds:e.shiftKey?[...new Set([...selection.objectIds,object.id])]:[object.id],edgeId:object.edgeIds[0]});const n=doc.master.geometry.edges[object.edgeIds[0]]?.nodeIds[0];if(n)view('focus',doc.master.geometry.nodes[n].p);}} onDoubleClick={()=>{const name=prompt('Object name',object.name);if(name?.trim())op({t:'renameObject',objectId:object.id,name:name.trim()});}}>{object.name}<small>{object.edgeIds.length} edges</small></button><button title={object.hidden?'Show object':'Hide object'} disabled={disabled} onClick={()=>op({t:'setObjectFlags',objectId:object.id,locked:object.locked,hidden:!object.hidden})}>{object.hidden?'◌':'◉'}</button><button title={object.locked?'Unlock object':'Lock object'} disabled={engine.busy||engine.readOnly} onClick={()=>op({t:'setObjectFlags',objectId:object.id,locked:!object.locked,hidden:object.hidden})}>{object.locked?'▣':'□'}</button></div>)}</div><p className="muted">Showing up to 180 matches. Shift-click selects several.</p></section></>}
        {tab==='output'&&<><section><h2>{doc.kind==='master'?'Create a size':'Size & machine'}</h2><label className="field">Machine<select value={profileId} onChange={e=>setProfileId(e.target.value)}>{settings.profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="segmented">{(['grid','in','cm','fit']as const).map(mode=><button key={mode} className={sizeMode===mode?'active':''} onClick={()=>{if(mode!==sizeMode){const current=resolved.value;setSizeMode(mode);setWidth(mode==='grid'?String(current?.widthPx??1200):String((current?.widthIn??2.5)*(mode==='cm'?2.54:1)));setHeight('');}}}>{mode==='grid'?'Hooks':mode==='fit'?'Fit across':mode}</button>)}</div>{sizeMode==='fit'?<label className="field">Repeats across<input type="number" min="1" value={across} onChange={e=>setAcross(e.target.value)}/></label>:<><div className="field-pair"><label className="field">Width<input type="number" min="0.01" value={width} onChange={e=>setWidth(e.target.value)}/></label><label className="field">Height<input type="number" min="0.01" placeholder={resolved.value?String(sizeMode==='grid'?resolved.value.heightPx:(resolved.value.heightIn*(sizeMode==='cm'?2.54:1)).toFixed(2)):''} value={linked?'':height} disabled={linked} onChange={e=>setHeight(e.target.value)}/></label></div><label className="check-row"><input type="checkbox" checked={linked} onChange={e=>{setLinked(e.target.checked);if(!e.target.checked&&resolved.value)setHeight(String(sizeMode==='grid'?resolved.value.heightPx:resolved.value.heightIn*(sizeMode==='cm'?2.54:1)));}}/>Keep design proportion</label></>}{resolved.value?<div className="size-result"><strong>{resolved.value.widthPx} × {resolved.value.heightPx}</strong><span>hooks × picks</span><p>{resolved.value.widthIn.toFixed(2)} × {resolved.value.heightIn.toFixed(2)} in · {profile.epi} EPI / {profile.ppi} PPI</p>{resolved.value.warnings.map(w=><p className="warning-text" key={w}>{w}</p>)}</div>:<p className="warning-text">{resolved.error}</p>}{doc.kind==='size'&&<button className="primary full" disabled={disabled||!resolved.value} onClick={()=>action({type:'size',sizeInput,profileId})}>Apply size</button>}<label className="field">New size name<input placeholder={resolved.value?`${resolved.value.widthPx} × ${resolved.value.heightPx}`:'Size name'} value={newName} onChange={e=>setNewName(e.target.value)}/></label><button className={doc.kind==='master'?'primary full':'full'} disabled={disabled||!resolved.value} onClick={()=>void createSize()}>{doc.kind==='master'?'Create size variant':'Create another size from master'}</button>{doc.kind==='size'&&<button className="text-button" disabled={disabled} onClick={()=>void rebase()}>Review update from current master →</button>}</section>
          {doc.kind==='size'&&<><section><h2>Pixel cleanup</h2><label className="field">Minimum region · pixels<input type="number" min="0" max="100" value={doc.rules.minRegionPx} disabled={disabled} onChange={e=>action({type:'rules',rules:{...doc.rules,minRegionPx:Number(e.target.value)}})}/></label><label className="field">Minimum thickness · pixels<input type="number" min="0" max="8" value={doc.rules.minThicknessPx} disabled={disabled} onChange={e=>action({type:'rules',rules:{...doc.rules,minThicknessPx:Number(e.target.value)}})}/></label>{(['removeCheckerboard','connectVisibleEdges4']as const).map(key=><label className="check-row" key={key}><input type="checkbox" checked={doc.rules[key]} disabled={disabled} onChange={e=>action({type:'rules',rules:{...doc.rules,[key]:e.target.checked}})}/>{key==='removeCheckerboard'?'Remove checkerboards':'Connect stroke pixels'}</label>)}<details className="palette-merge"><summary>Protect colors from cleanup</summary>{doc.master.palette.entries.map(entry=><label className="check-row" key={entry.index}><input type="checkbox" checked={doc.rules.protectedColorIndices?.includes(entry.index)??false} disabled={disabled} onChange={e=>action({type:'rules',rules:{...doc.rules,protectedColorIndices:e.target.checked?[...(doc.rules.protectedColorIndices??[]),entry.index]:(doc.rules.protectedColorIndices??[]).filter(i=>i!==entry.index)}})}/>{entry.index} · {entry.name}</label>)}</details><p className="muted">Cleanup applies only to this size. Pixel pencil overrides apply last.</p>{doc.pixelOverrides.length>0&&<button disabled={disabled} onClick={()=>action({type:'pixels',pixels:doc.pixelOverrides.map(p=>({...p,colorIndex:null}))})}>Clear {doc.pixelOverrides.length} pixel overrides</button>}</section><section><h2>Exports</h2><button className="primary full" disabled={disabled||exporting} onClick={()=>void exportDesign()}>{exporting?'Exporting…':'Export BMP'}</button><div className="export-list">{exports.map(e=><div key={e.id}><strong>{e.widthPx} × {e.heightPx}</strong><small>{new Date(e.createdAt).toLocaleString()}</small><p>{(['bmp','png','json']as const).map(format=><a key={format} href={`/api/designs/${doc.id}/exports/${e.id}/${format}`} download>{format.toUpperCase()}</a>)}</p></div>)}</div></section></>}
        </>}
        {tab==='history'&&<><section><h2>Version history</h2><p className="muted">Autosave keeps your draft. Save a version to keep a named checkpoint.</p><label className="field">Version note<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Coloring complete…"/></label><button className="primary full" disabled={disabled||savingVersion} onClick={()=>void saveVersion()}>Save version</button><div className="version-list">{versions.map(v=><article key={v.id}><strong>Version {v.version}</strong><p>{v.note}</p><small>{new Date(v.createdAt).toLocaleString()}</small><div className="button-row"><button disabled={engine.busy} onClick={()=>void compareVersion(v.id,`Version ${v.version} · ${v.note}`)}>Compare</button><button disabled={disabled} onClick={()=>void restore(v.id)}>Restore</button></div></article>)}</div></section></>}
        <section className="warnings-section"><details><summary>Design notes <span>{engine.state?.warnings.length??0}</span></summary>{engine.state?.render.report.unassignedFaces?<button disabled={disabled} onClick={()=>{const face=engine.geometry?.faces.find(f=>f.outer&&doc.master.geometry.faceColors[f.id]?.colorIndex==null);if(face){view('focus',face.ref);setTool('fill');}}}>Find an unassigned region</button>:null}<ul>{engine.state?.warnings.slice(0,30).map((warning,i)=><li key={i}>{warning}</li>)}</ul>{engine.state?.render.report.smallFacesRemoved.length?<button onClick={()=>view('focus',engine.state!.render.report.smallFacesRemoved[0])}>Inspect a small detail</button>:null}</details></section>
      </aside></div><footer className="editor-status"><span>{tools.find(t=>t.id===tool)?.label} {engine.readOnly?'· Read-only':engine.busy?'· Updating…':engine.renderPending?'· Finalizing pixel preview…':''}</span><span>{engine.state?`${engine.state.stats.faces.toLocaleString()} regions · ${engine.state.stats.edges.toLocaleString()} strokes · ${engine.state.render.widthPx} × ${engine.state.render.heightPx} ${doc.kind==='master'?'preview':'pixels'}`:'Preparing geometry…'}</span><span>Six colors · Local workspace</span></footer></div>;
}
