import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,mkdtemp} from 'node:fs/promises';
import path from 'node:path';
import {createServer,build as viteBuild,type ViteDevServer} from 'vite';
import {chromium} from 'playwright';
import {materializeGeometry} from '../packages/core/src/materialize';
import {flattenEdge} from '../packages/core/src/topology';
import {render} from '../packages/core/src/render';
import {resolveSize} from '../packages/core/src/size';
import {DEFAULT_PROFILE,DEFAULT_RULES,type Master} from '../packages/core/src/types';
import {createApp} from '../apps/server/src/app';
import {checkIntegratedDrags} from './fixtures/canvas-integration-check';

// tsx scripts/test-canvas-preview.ts [master.json] [output-directory] [--integrated]
// Reads source fixtures only. This deliberately delays optimistic commits and never settles
// the raster, isolating actual DesignCanvas presentation from background-worker performance.
const args=process.argv.slice(2).filter(arg=>arg!=='--integrated'),integrated=process.argv.includes('--integrated'),root=process.cwd(),masterPath=path.resolve(args[0]??'output/stroke-trial/sample-1-bb1795/master.json'),output=path.resolve(args[1]??'output/canvas-preview');
const master=JSON.parse(await readFile(masterPath,'utf8')) as Master,prepared=integrated?undefined:materializeGeometry(master);if(prepared)master.geometry=prepared.geometry;
const sizeInput={mode:'grid' as const,widthPx:1200,linkAspect:true},profile=DEFAULT_PROFILE,size=resolveSize(master.bounds,profile,sizeInput),raster=prepared?render(master.geometry,prepared.faces,master.bounds,master.palette,size.widthPx,size.heightPx,DEFAULT_RULES,[],master.repeat):undefined;
const nodes=Object.values(master.geometry.nodes),point=nodes.reduce((a,b)=>(a.p.x-master.bounds.w/2)**2+(a.p.y-master.bounds.h/2)**2<(b.p.x-master.bounds.w/2)**2+(b.p.y-master.bounds.h/2)**2?a:b),edge=Object.values(master.geometry.edges).find(edge=>edge.nodeIds.includes(point.id))!,owner=master.objects.find(object=>object.edgeIds.includes(edge.id));
const document={id:master.id,kind:'master',name:master.name,tags:[],master,profileId:profile.id,sizeInput,rules:DEFAULT_RULES,pixelOverrides:[],operations:[],revision:1,createdAt:master.createdAt,updatedAt:master.updatedAt};
const fixture={document,geometry:{paths:integrated?{}:Object.fromEntries(Object.values(master.geometry.edges).map(edge=>[edge.id,flattenEdge(edge,master.geometry,.25)])),faces:prepared?.faces??[]},render:{widthPx:size.widthPx,heightPx:size.heightPx,widthIn:size.widthIn,heightIn:size.heightIn,epi:profile.epi,ppi:profile.ppi,preview:true,renderMs:0,report:{...raster?.report,changedPixelsMask:undefined}},grid:Buffer.from(raster?.grid??new Uint8Array()).toString('base64'),selection:{edgeId:edge.id,nodeId:point.id,objectIds:owner?[owner.id]:[]},point:point.p};
let apiApp:Awaited<ReturnType<typeof createApp>>|undefined,apiAddress='',server:ViteDevServer|undefined,address='http://127.0.0.1:5191';await mkdir(output,{recursive:true});
const entryHtml='<!doctype html><html><head><style>body{margin:0}.canvas-host{height:900px;width:1400px;flex:1}</style></head><body><div id="root"></div><script type="module" src="/scripts/fixtures/canvas-preview-harness.tsx"></script></body></html>';
if(integrated){
  await mkdir(path.join(root,'.cache/canvas-integration'),{recursive:true});const runDir=await mkdtemp(path.join(root,'.cache/canvas-integration/run-')),web=path.join(runDir,'web'),entry=path.join(runDir,'canvas-benchmark.html');await mkdir(web,{recursive:true});await writeFile(entry,entryHtml);console.log('Building production harness');await viteBuild({root,configFile:path.join(root,'apps/web/vite.config.ts'),logLevel:'warn',build:{outDir:web,emptyOutDir:false,rollupOptions:{input:entry}}});const html=await readFile(path.join(web,path.relative(root,entry)),'utf8');
  apiApp=await createApp({dataDir:path.join(runDir,'data'),staticDir:web});apiApp.get('/canvas-benchmark',(_request,reply)=>reply.type('text/html').send(html));apiApp.get('/canvas-fixture',()=>fixture);
  const response=await apiApp.inject({method:'POST',url:'/api/designs',payload:{master,name:'Canvas integration scratch fixture'}});if(response.statusCode!==200&&response.statusCode!==201)throw new Error(response.body);Object.assign(document,response.json());Object.assign(fixture,{integrated:true,settings:(await apiApp.inject({method:'GET',url:'/api/workspace'})).json()});apiAddress=await apiApp.listen({host:'127.0.0.1',port:0});address=apiAddress;
}else{
  const fixtureJson=JSON.stringify(fixture);server=await createServer({root,configFile:path.join(root,'apps/web/vite.config.ts'),server:{host:'127.0.0.1',port:5191,strictPort:true,hmr:false},plugins:[{name:'canvas-benchmark',configureServer(server){server.middlewares.use(async(req,res,next)=>{if(req.url==='/canvas-fixture'){res.setHeader('Content-Type','application/json');res.end(fixtureJson);return;}if(req.url!=='/canvas-benchmark')return next();res.setHeader('Content-Type','text/html');res.end(await server.transformIndexHtml('/canvas-benchmark',entryHtml));});}}]});await server.listen();
}
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const stats=(values:number[])=>{const sorted=[...values].sort((a,b)=>a-b);return{count:values.length,p50Ms:sorted[Math.floor(sorted.length*.5)],p95Ms:sorted[Math.floor(sorted.length*.95)],maxMs:sorted.at(-1),over100Ms:values.filter(value=>value>100).length};};
try{
  const page=await browser.newPage({viewport:{width:1400,height:900}}),errors:string[]=[];await page.addInitScript(()=>{(window as any).__name=(value:unknown)=>value;});page.setDefaultTimeout(120_000);page.on('pageerror',error=>{errors.push(error.message);console.error(error.message);});page.on('console',message=>{if(message.type()==='error')console.error(message.text());});console.log('Opening canvas harness',address);await page.goto(`${address}/canvas-benchmark`);await page.waitForFunction(()=>(window as any).ready||(window as any).error);const initialError=await page.evaluate(()=>(window as any).error);if(initialError)throw new Error(initialError);console.log('Editor ready');await page.waitForFunction(()=>(window as any).__JDM_CANVAS_METRICS__.length>0);
  const checks=await page.evaluate(()=>(window as any).runPreviewChecks());
  await page.evaluate(()=>{(window as any).choose((window as any).fixture.selection.nodeId);});await page.waitForTimeout(250);
  if(integrated){const report={masterPath,nodes:nodes.length,edges:Object.keys(master.geometry.edges).length,...await checkIntegratedDrags(page,apiAddress,point.id),previewChecks:checks,browserErrors:errors};await page.screenshot({path:path.join(output,'integration.png')});await writeFile(path.join(output,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));assert.deepEqual(errors,[]);}else{
  const canvas=page.locator('canvas[aria-label="Design canvas"]'),box=await canvas.boundingBox();assert(box);const x=box.x+box.width/2,y=box.y+box.height/2;
  const digest=()=>canvas.evaluate(async(canvas:HTMLCanvasElement)=>{const data=canvas.getContext('2d')!.getImageData(0,0,canvas.width,canvas.height).data;return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',data))).map(byte=>byte.toString(16).padStart(2,'0')).join('');});
  await canvas.evaluate(canvas=>{const state=window as any;state.__JDM_PAINT_METRICS__=[];state.__JDM_EVENT_QUEUE__=[];canvas.addEventListener('pointermove',event=>{if(!(event as PointerEvent).buttons)return;const timestamp=event.timeStamp,handled=performance.now();requestAnimationFrame(()=>requestAnimationFrame(()=>{state.__JDM_PAINT_METRICS__.push(performance.now()-timestamp);state.__JDM_EVENT_QUEUE__.push(handled-timestamp);}));});});
  const before=await digest();await page.evaluate(()=>{(window as any).__JDM_CANVAS_METRICS__=[];});await page.mouse.move(x,y);await page.mouse.down();
  for(let i=1;i<=60;i++){await page.mouse.move(x+i*2,y+Math.sin(i/15)*25);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve())));}
  const during=await digest();assert.notEqual(during,before,'Dragging must visibly alter the geometry before commit');await page.screenshot({path:path.join(output,'dragging.png')});await page.mouse.up();await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve())));const afterRelease=await digest();assert.equal(afterRelease,during,'Pointer release must retain the immediate preview while the document is delayed');
  await page.waitForFunction(()=>(window as any).actions.length===1);const action=await page.evaluate(()=>(window as any).actions[0]);assert.equal(action.operation.t,'moveNodes');await page.waitForTimeout(650);assert.notEqual(await digest(),before,'Optimistic document must preserve moved geometry until raster settlement');await page.screenshot({path:path.join(output,'pending.png')});
  const metrics=await page.evaluate(()=>({cpu:(window as any).__JDM_CANVAS_METRICS__,paint:(window as any).__JDM_PAINT_METRICS__,queue:(window as any).__JDM_EVENT_QUEUE__})) as {cpu:number[];paint:number[];queue:number[]};
  await page.evaluate(()=>{(window as any).commitDelay=5000;});const heldY=y+Math.sin(4)*25;for(let n=0;n<2;n++){await page.mouse.move(x+120+n*20,heldY+n*10);await page.mouse.down();await page.mouse.move(x+140+n*20,heldY+10+n*10);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve())));await page.mouse.up();await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve())));}
  const rapid=await page.evaluate(()=>(window as any).actions);assert.equal(rapid.length,3,'The next drag must hit the retained node before an optimistic model update');assert.equal(rapid[2].operation.t,'moveNodes');assert(rapid[2].operation.nodes[0].to.x>rapid[1].operation.nodes[0].to.x,'Successive retained drags must accumulate');checks.push('successive pointer drags hit and accumulate before optimistic model updates');
  const report={masterPath,nodes:nodes.length,edges:Object.keys(master.geometry.edges).length,faces:prepared!.faces.length,selectedObjectEdges:owner?.edgeIds.length??1,target:{nodeId:point.id,edgeId:edge.id,objectId:owner?.id,sourcePoint:point.p,screenPoint:{x,y},selector:'canvas[aria-label="Design canvas"]'},timingScope:{cpu:'Main-thread draw callback CPU time.',paint:'Pointer event timestamp to second requestAnimationFrame after draw; presentation proxy in headless Edge, not measured monitor scanout.'},firstDrawCpuMs:metrics.cpu[0],steadyDrawCpu:stats(metrics.cpu.slice(1)),eventToPaintProxy:stats(metrics.paint),eventQueue:stats(metrics.queue),noSnapBack:true,previewChecks:checks,browserErrors:errors};
  assert.deepEqual(errors,[]);await writeFile(path.join(output,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));assert(report.steadyDrawCpu.p95Ms<33,'Dense canvas steady preview draw CPU should stay below 33 ms');assert.equal(report.eventToPaintProxy.over100Ms,0,'No pointer preview should wait over 100 ms in the isolated canvas benchmark');
  }
}finally{await browser.close();await server?.close();await apiApp?.close();}

